#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run build || 
(
    echo '🏗️ 👷 Better call Bob... your build failed. Fix your build and try pushing again
            Are you seriously trying to write that? Make the changes required above.'
    false;
)

"✅ Build successful - pushing now... oh and... have a cookie! 🍪"